config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'hello#index'

  get '/intake', to: 'intake#new'
  post '/intake', to: 'intake#create'
  get '/builder', to: 'builder#index'
  get '/questions',  to: 'questions#index'
  post '/questions', to: 'questions#create'
  get '/questions/download_csv', to: 'questions#download_csv'
  put '/questionnaire/:id', to: 'questionnaire#update'
  get '/questionnaire/:id', to: 'questionnaire#show'
  get '/questionnaire/:id/redcap', to: 'questionnaire#redcap'

  # menu_items are currently not supported
  # resources :menu_items, only: [:index, :new, :create]
  # get '/menu_items/show_new', to: 'menu_items#show_new'

  # get '/questionnaire/standard', to: 'questionnaire#standard'

  namespace :admin do
    get '/dashboard', to: 'dashboard#index'
    post '/dashboard', to: 'dashboard#upload'
    get '/dashboard/sample_csv', to: 'dashboard#sample_csv'

    namespace :dashboard do
      resources :tags
      resources :questions, only: [:index, :destroy]
      get '/questions/nuke', to: 'questions#nuke'
    end
  end
end

app/controllers/admin/dashboard/questions_controller.rb
module Admin
  module Dashboard
    class QuestionsController < ApplicationController
      def index
        @questions = Question.all
      end

      def destroy
        question = Question.find(params['id'])
        if question.children.present?
          flash[:error] =
            "Question ##{question.id} has children questions and cannot be deleted. Please remove questions with parent ##{question.id} first and then try again."
        else
          question.destroy!
          flash[:success] = "Successfully deleted question ##{question.id}"
        end

        redirect_to admin_dashboard_questions_path
      end

      def nuke
        Intake.destroy_all
        QuestionnaireQuestion.destroy_all
        Questionnaire.destroy_all
        Tagging.destroy_all
        Question.destroy_all

        redirect_to admin_dashboard_questions_path
      end
    end
  end
end

app/controllers/admin/dashboard_controller.rb
module Admin
  class DashboardController < ApplicationController
    def index
      @headers = ['ID', 'Question group', 'Section', 'Question', 'Mandatory', 'Field Type', 'Choices, Calculations, OR Slider Labels', 'Tag1', 'Tag2',
                  'Variable / Field Name', 'Form Name', 'SectionHeader', 'Field Label', 'Field Note', 'Text Validation Type OR Show Slider Number',
                  'Text Validation Min', 'Text Validation Max', 'Identifier?', 'Branching Logic (Show field only if...)', 'Required Field?',
                  'Custom Alignment', 'Question Number (surveys only)', 'Matrix Group Name', 'Matrix Ranking?', 'Field Annotation']
    end

    def upload
      result = Services::CsvImporter.new(csv_contents).import!
      if result == 'success'
        flash[:success] = 'CSV import successful!'
      else
        flash[:error] = "CSV import failed: #{result}"
      end
      redirect_to action: :index
    end

    def sample_csv
      respond_to do |format|
        format.csv do
          response.headers['Content-Type'] = 'text/csv'
          response.headers['Content-Disposition'] = 'attachment; filename=example_questions.csv'
          render template: '/admin/dashboard/example_csv.csv.erb'
        end
      end
    end

    private

    def csv_contents
      input_file.read
    end

    def input_file
      params['file']
    end
  end
end

app/views/admin/dashboard/example_csv.csv.erb
ID,Question group,Section,Question,Mandatory,Field Type,"Choices, Calculations, OR Slider Labels",Tag1,Tag2,Tag3,Tag4,Tag5,Tag6,Variable / Field Name,Form Name,SectionHeader,Field Label,Field Note,Text Validation Type OR Show Slider Number,Text Validation Min,Text Validation Max,Identifier?,Branching Logic (Show field only if...),Required Field?,Custom Alignment,Question Number (surveys only),Matrix Group Name,Matrix Ranking?,Field Annotation
101,,Screening,Order any takeout from [restaurant] since [date]?,Y,radio,"Y, Yes | N, No | U, Unknown",Restaurant,Take-out,,,,,order_takeout,questionnaire_tool,,,,,,,,,Y,,,,,
102,101,Screening,"If yes, on which day?",,text,,,,,,,,oreder_takeout_day,questionnaire_tool,,,,,,,,,,,,,,

app/views/admin/dashboard/index.html.erb
<div class="container">
  <h1 class="title">Question Import</h1>
    <%= form_tag({action: :upload}, multipart: true, method:'post') do %>
      <div class="field">
        <div>
          <%= label_tag('input_file', 'Select a CSV to upload', class: 'label') %>
          <%= file_field_tag 'file', required: true %>
        </div>
      </div>
      <div class="control">
        <%= submit_tag('Submit', class: 'button is-primary') %>
      </div>
    <% end %>
</div>
<br>

<div class="container">
<h5 class="title is-5">
  Question Import Rules:
</h5>
<p>
  For successful import, file must be a CSV (.csv exstension) and follow the rules for each column type below:
</p>
<div class="table-container">
  <table class="table is-bordered is-fullwidth is-hoverable">
    <thead>
      <% @headers.each do |header| %>
        <th><%= String(header) %></th>
      <% end %>
    </thead>
    <tbody>
        <tr>
          <td>
            <li> Must be a number</li>
            <li> Must be unique</li>
          </td>
          <td>
            <li>Must be an ID of existing parent question</li>
            <li>Child question row must come <em>after</em> parent question</li>
          </td>
          <td>
            <li>Must be one of these values: <b>Contact</b>, <b>Introduction</b>, <b>Screening</b>, <b>Exposure</b>, <b>Other</b>, <b>Symptoms</b>, <b>Onset_duration</b>, <b>Outcomes</b>, <b>Demographics</b></li>
          </td>
          <td>
          </td>
          <td>
            <li><b>Y</b> will mark question as mandatory. Any other value will not.</li>
            <li>Mandatory questions will automatically appear on every questionnaire highlighted in gray.</li>
          </td>
          <td>
            <li>Must be one of these values: <b>radio</b>, <b>checkbox</b>, <b>text</b>, <b>number</b>, <b>instructions</b></li>
          </td>
          <td>
            <li>Choices must be separated with a <b>|</b></li>
          </td>
          <td>
            <li><a href="/admin/dashboard/tags">See list of valid tags</a></li>
            <li>Questions that should appear on every questionnaire must have tag <b>universal</b></li>
          </td>
          <td>
            Redcap field
          </td>
          <td>
            Redcap field
          </td>
          <td>
            Redcap field
          </td>
          <td>
            Redcap field
          </td>
          <td>
            Redcap field
          </td>
          <td>
            Redcap field
          </td>
          <td>
            Redcap field
          </td>
          <td>
            Redcap field
          </td>
          <td>
            Redcap field
          </td>
          <td>
            Redcap field
          </td>
          <td>
            Redcap field
          </td>
          <td>
            Redcap field
          </td>
          <td>
            Redcap field
          </td>
          <td>
            Redcap field
          </td>
          <td>
            Redcap field
          </td>
          <td>
            Redcap field
          </td>
          <td>
            Redcap field
          </td>
        </tr>
    </tbody>
  </table>
</div>
<h5 class="title is-5">
  <p><%= link_to "Click here to download example CSV", admin_dashboard_sample_csv_path(:format => "csv")%></p>
</h5>
<div>
<div class="container">
  <div class="field is-grouped">
    <button class="button">
      <a class="html-link" href="/admin/dashboard/questions">View Imported Questions</a>
    </button>
    <button class="button ">
      <a class="html-link" href="/">Back</a>
    </button>
  </div>
</div>